name: weeek_checker workflow

on: [push]

jobs:

  build_weeek:
    name: Push Docker project image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/weeek_checker:latest

#  deploy:
#    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    needs:
#      - build_weeek
#    steps:
#      - name: executing remote ssh commands to deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_KEY }}
#          passphrase: ${{ secrets.PASSPHRASE }}
#          script: |
#            cd infra
#            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/english_brake_fast:latest
#            sudo docker-compose stop
#            sudo docker-compose rm english
#            touch .env
#            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
#            echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
#            echo TELEGRAM_TO=${{ secrets.TELEGRAM_TO }} >> .env
#            echo ALEXEY_ID=${{ secrets.ALEXEY_ID }} >> .env
#            echo DMITRY_ID=${{ secrets.DMITRY_ID }} >> .env
#            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
#            echo DB_NAME=${{ secrets.DB_NAME }} >> .env
#            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
#            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
#            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
#            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
#            sudo docker-compose up -d
#            sudo docker-compose exec -T english python manage.py makemigrations --noinput
#            sudo docker-compose exec -T english python manage.py migrate --noinput
#            sudo docker-compose exec -T english python manage.py collectstatic --no-input

  send_message:
    runs-on: ubuntu-latest
    needs: build_weeek
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!